### PR TITLE
IDEA window builder GUI

### PR DESCRIPTION
**Pull request by Nivirx**
This version of the GUI was built with the IDEA Swing UI designer and should be able to be compiled for non-Idea IDE users as well.

### CODE REVIEW

**Review by DDKGM — COMMENTED** [review]
Is the query table supposed to always show or are you doing that to test?

**Comment by Nivirx** [comment]
Yes, I didn't see any reason to hide the table even if it is empty. Once we have a solid API for searching we can make the table more representative of our data.

**Comment by Nivirx** [comment]
I guess we are just merging this in then...

**Comment by DDKGM** [comment]
Yeah, It looks good to me.

**Comment by DDKGM** [comment]
You didn't use the GUI builder right? You just coded the GUI?

**Comment by Nivirx** [comment]
This is the IDEA UI Designer but It is setup to output to Java Source.

**Comment by DDKGM** [comment]
I have no idea. Git kept asking me to merge, and I thought I was merging my master branch with what you did. Is that not what happened?

**Comment by DDKGM** [comment]
Oh, I see. I was trying to go in the GUI designer for NetBeans, and since you did it that way I can't go in and add to it unless I hard-code. No biggie.

**Pull request merged**
