### PR TITLE
Master merge and rebase

### PR DESCRIPTION
**Pull request by Nivirx**
I was able to merge everyone's branch into a single branch and rebase them to the current
origin/master to allow for a successful merge.

@LlanerasJ 
Your branch was able to be merged mostly as-is except for main.java

@DDKGM 
I had to do a squash commit (packs all commits into one) for your branch because it had different
types of conflicts. but I was still able to add it to this single branch.

I left all of the code you both wrote in your respective packages (minus conflicts) and then merged my branch on top. you should (in theory) be able to change the main method in the searchUI and be able to use your UI versions as is.

### CODE REVIEW

**Comment by DDKGM** [comment]
You can't see me but I am bowing to the Git Guru lol

**Comment by LlanerasJ** [comment]
Sounds good so all we have to do is change or main class to be able to run the project?

**Review by LlanerasJ — APPROVED** [review]
Looks great!

**Comment by Nivirx** [comment]
Yes that should be it, It wouldn't be that hard to work it into the java preferences api either so we could store it. Once i am off lunch i will make the required tags and releases for tonight.

**Pull request merged**
